### ISSUE TITLE
Deploy can't connect to Freenas server

### ISSUE THREAD

**Issue by HansHM** [danb35/deploy-freenas#17]
I try to deploy my letsencrypt Cert, But when running deplay_freenas.py, i got a connection error.

I tried, localhost, local ip 169.178.178.129 and the remote ip.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141,                                                                                                                                                              in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line                                                                                                                                                              83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line                                                                                                                                                              73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 284,                                                                                                                                                              in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150,                                                                                                                                                              in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnecti                                                                                                                                                             on object at 0x807a747f0>: Failed to establish a new connection: [Errno 61] Conn                                                                                                                                                             ection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440,                                                                                                                                                              in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388,                                                                                                                                                              in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443                                                                                                                                                             ): Max retries exceeded with url: /api/v1.0/system/certificate/import/ (Caused b                                                                                                                                                             y NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x80                                                                                                                                                             7a747f0>: Failed to establish a new connection: [Errno 61] Connection refused',)                                                                                                                                                             )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./deploy_freenas/deploy_freenas.py", line 73, in <module>
    "cert_privatekey": priv_key,
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in po                                                                                                                                                             st
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in req                                                                                                                                                             uest
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508,                                                                                                                                                              in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618,                                                                                                                                                              in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508,                                                                                                                                                              in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=                                                                                                                                                             443): Max retries exceeded with url: /api/v1.0/system/certificate/import/ (Cause                                                                                                                                                             d by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0                                                                                                                                                             x807a747f0>: Failed to establish a new connection: [Errno 61] Connection refused                                                                                                                                                             ',))

**Comment by danb35** [comment]
Are you running `deploy_freenas.py` on your FreeNAS box?  If so, I'd leave
it at localhost.  It looks like it's failing to connect to your GUI on port
443--do you already have HTTPS enabled on the machine, and if so, is it
listening on port 443?  If either of those is not the case, you'll need to
adjust the configuration accordingly.

**Comment by HansHM** [comment]
Hello danb35,

Yes i run it on the Freenas and have now running the GUI whit a self signed cert, whit out it, it is impossible to turn on https for the GUI.

But even now he is reduced to connect.
